// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_function_top_function_Pipeline_VITIS_LOOP_100_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_reload30,
        visited_address0,
        visited_ce0,
        visited_we0,
        visited_d0,
        visited_q0,
        visited_address1,
        visited_ce1,
        visited_we1,
        visited_d1,
        visited_q1,
        nodeQueue_address0,
        nodeQueue_ce0,
        nodeQueue_we0,
        nodeQueue_d0,
        nodeQueue_q0,
        p_out,
        p_out_ap_vld,
        adjacencyList_18_address0,
        adjacencyList_18_ce0,
        adjacencyList_18_q0,
        adjacencyList_16_address0,
        adjacencyList_16_ce0,
        adjacencyList_16_q0,
        adjacencyList_15_address0,
        adjacencyList_15_ce0,
        adjacencyList_15_q0,
        adjacencyList_13_address0,
        adjacencyList_13_ce0,
        adjacencyList_13_q0,
        adjacencyList_11_address0,
        adjacencyList_11_ce0,
        adjacencyList_11_q0,
        adjacencyList_7_address0,
        adjacencyList_7_ce0,
        adjacencyList_7_q0,
        adjacencyList_4_address0,
        adjacencyList_4_ce0,
        adjacencyList_4_q0,
        adjacencyList_3_address0,
        adjacencyList_3_ce0,
        adjacencyList_3_q0,
        adjacencyList_2_address0,
        adjacencyList_2_ce0,
        adjacencyList_2_q0,
        traversalSize_i,
        traversalSize_o,
        traversalSize_o_ap_vld,
        allTraversal_address0,
        allTraversal_ce0,
        allTraversal_we0,
        allTraversal_d0,
        adjacencyList_1_address0,
        adjacencyList_1_ce0,
        adjacencyList_1_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 13'd1;
parameter    ap_ST_fsm_pp0_stage1 = 13'd2;
parameter    ap_ST_fsm_pp0_stage2 = 13'd4;
parameter    ap_ST_fsm_pp0_stage3 = 13'd8;
parameter    ap_ST_fsm_pp0_stage4 = 13'd16;
parameter    ap_ST_fsm_pp0_stage5 = 13'd32;
parameter    ap_ST_fsm_pp0_stage6 = 13'd64;
parameter    ap_ST_fsm_pp0_stage7 = 13'd128;
parameter    ap_ST_fsm_pp0_stage8 = 13'd256;
parameter    ap_ST_fsm_pp0_stage9 = 13'd512;
parameter    ap_ST_fsm_pp0_stage10 = 13'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 13'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_reload30;
output  [4:0] visited_address0;
output   visited_ce0;
output   visited_we0;
output  [0:0] visited_d0;
input  [0:0] visited_q0;
output  [4:0] visited_address1;
output   visited_ce1;
output   visited_we1;
output  [0:0] visited_d1;
input  [0:0] visited_q1;
output  [4:0] nodeQueue_address0;
output   nodeQueue_ce0;
output   nodeQueue_we0;
output  [4:0] nodeQueue_d0;
input  [4:0] nodeQueue_q0;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [4:0] adjacencyList_18_address0;
output   adjacencyList_18_ce0;
input  [0:0] adjacencyList_18_q0;
output  [4:0] adjacencyList_16_address0;
output   adjacencyList_16_ce0;
input  [0:0] adjacencyList_16_q0;
output  [4:0] adjacencyList_15_address0;
output   adjacencyList_15_ce0;
input  [0:0] adjacencyList_15_q0;
output  [4:0] adjacencyList_13_address0;
output   adjacencyList_13_ce0;
input  [0:0] adjacencyList_13_q0;
output  [4:0] adjacencyList_11_address0;
output   adjacencyList_11_ce0;
input  [0:0] adjacencyList_11_q0;
output  [4:0] adjacencyList_7_address0;
output   adjacencyList_7_ce0;
input  [0:0] adjacencyList_7_q0;
output  [4:0] adjacencyList_4_address0;
output   adjacencyList_4_ce0;
input  [0:0] adjacencyList_4_q0;
output  [4:0] adjacencyList_3_address0;
output   adjacencyList_3_ce0;
input  [0:0] adjacencyList_3_q0;
output  [4:0] adjacencyList_2_address0;
output   adjacencyList_2_ce0;
input  [0:0] adjacencyList_2_q0;
input  [31:0] traversalSize_i;
output  [31:0] traversalSize_o;
output   traversalSize_o_ap_vld;
output  [4:0] allTraversal_address0;
output   allTraversal_ce0;
output   allTraversal_we0;
output  [4:0] allTraversal_d0;
output  [4:0] adjacencyList_1_address0;
output   adjacencyList_1_ce0;
input  [0:0] adjacencyList_1_q0;

reg ap_idle;
reg[4:0] visited_address0;
reg visited_ce0;
reg visited_we0;
reg[4:0] visited_address1;
reg visited_ce1;
reg visited_we1;
reg[4:0] nodeQueue_address0;
reg nodeQueue_ce0;
reg nodeQueue_we0;
reg[4:0] nodeQueue_d0;
reg p_out_ap_vld;
reg adjacencyList_18_ce0;
reg adjacencyList_16_ce0;
reg adjacencyList_15_ce0;
reg adjacencyList_13_ce0;
reg adjacencyList_11_ce0;
reg adjacencyList_7_ce0;
reg adjacencyList_4_ce0;
reg adjacencyList_3_ce0;
reg adjacencyList_2_ce0;
reg[31:0] traversalSize_o;
reg traversalSize_o_ap_vld;
reg allTraversal_ce0;
reg allTraversal_we0;
reg adjacencyList_1_ce0;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln100_fu_618_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_state13_pp0_stage12_iter0;
wire    ap_block_pp0_stage12_subdone;
reg   [31:0] rear_7_1_reg_470;
reg   [31:0] rear_7_3_reg_497;
reg   [31:0] rear_7_6_reg_511;
reg   [31:0] rear_7_15_reg_566;
reg   [31:0] rear_reg_814;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln100_reg_871;
wire   [63:0] add_ln101_fu_624_p2;
reg   [63:0] add_ln101_reg_875;
reg   [31:0] traversalSize_load_reg_885;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_pp0_stage2_11001;
wire   [31:0] add_ln102_fu_654_p2;
reg   [31:0] add_ln102_reg_940;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_pp0_stage3_11001;
reg   [0:0] adjacencyList_1_load_reg_945;
reg   [0:0] adjacencyList_2_load_reg_949;
reg   [0:0] adjacencyList_3_load_reg_953;
reg   [0:0] adjacencyList_4_load_reg_957;
reg   [0:0] adjacencyList_7_load_reg_961;
reg   [0:0] adjacencyList_11_load_reg_965;
reg   [0:0] adjacencyList_13_load_reg_969;
reg   [0:0] adjacencyList_15_load_reg_973;
reg   [0:0] adjacencyList_16_load_reg_977;
reg   [0:0] adjacencyList_18_load_reg_981;
reg   [0:0] visited_load_reg_985;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_pp0_stage4_11001;
reg   [0:0] visited_load_1_reg_989;
wire   [31:0] add_ln107_1_fu_676_p2;
reg   [31:0] add_ln107_1_reg_993;
reg   [0:0] visited_load_2_reg_998;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_pp0_stage5_11001;
wire   [31:0] add_ln107_2_fu_687_p2;
reg   [31:0] add_ln107_2_reg_1002;
reg   [0:0] visited_load_3_reg_1007;
wire   [31:0] add_ln107_3_fu_694_p2;
reg   [31:0] add_ln107_3_reg_1011;
reg   [0:0] visited_load_4_reg_1016;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_pp0_stage6_11001;
reg   [0:0] visited_load_5_reg_1020;
wire   [31:0] add_ln107_4_fu_709_p2;
reg   [31:0] add_ln107_4_reg_1024;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_pp0_stage7_11001;
reg   [0:0] visited_load_6_reg_1030;
reg   [0:0] visited_load_7_reg_1034;
reg   [0:0] visited_load_8_reg_1038;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state9_pp0_stage8_iter0;
wire    ap_block_pp0_stage8_11001;
reg   [0:0] visited_load_9_reg_1042;
wire   [31:0] add_ln107_5_fu_719_p2;
reg   [31:0] add_ln107_5_reg_1046;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_state10_pp0_stage9_iter0;
wire    ap_block_pp0_stage9_11001;
wire   [31:0] add_ln107_6_fu_730_p2;
reg   [31:0] add_ln107_6_reg_1051;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_state11_pp0_stage10_iter0;
wire    ap_block_pp0_stage10_11001;
wire   [31:0] add_ln107_7_fu_741_p2;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_state12_pp0_stage11_iter0;
wire    ap_block_pp0_stage11_11001;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state14_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg   [31:0] ap_phi_mux_rear_7_0_phi_fu_462_p6;
wire   [31:0] add_ln107_fu_665_p2;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_7_0_reg_459;
reg   [31:0] ap_phi_mux_rear_7_1_phi_fu_473_p6;
wire   [31:0] ap_phi_reg_pp0_iter0_rear_7_1_reg_470;
reg   [31:0] ap_phi_mux_rear_7_2_phi_fu_487_p6;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_7_2_reg_484;
reg   [31:0] ap_phi_mux_rear_7_3_phi_fu_500_p6;
wire   [31:0] ap_phi_reg_pp0_iter0_rear_7_3_reg_497;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_7_6_reg_511;
reg   [31:0] ap_phi_mux_rear_7_10_phi_fu_528_p6;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_7_10_reg_525;
reg   [31:0] ap_phi_mux_rear_7_12_phi_fu_542_p6;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_7_12_reg_539;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_7_14_reg_553;
wire    ap_block_pp0_stage12_11001;
reg   [31:0] ap_phi_mux_rear_7_15_phi_fu_569_p6;
wire   [31:0] add_ln107_8_fu_752_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_rear_7_15_reg_566;
reg   [31:0] ap_phi_mux_rear_7_17_phi_fu_583_p6;
wire   [31:0] add_ln107_9_fu_764_p2;
reg   [31:0] ap_phi_reg_pp0_iter1_rear_7_17_reg_580;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] ap_phi_reg_pp0_iter0_rear_7_17_reg_580;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln102_fu_635_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] idxprom10_i64_cast_fu_640_p1;
wire   [63:0] zext_ln107_fu_671_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln107_1_fu_683_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln107_2_fu_701_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln107_3_fu_705_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln107_4_fu_715_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln107_5_fu_725_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln107_6_fu_736_p1;
wire    ap_block_pp0_stage10;
wire   [63:0] zext_ln107_7_fu_747_p1;
wire    ap_block_pp0_stage11;
wire   [63:0] zext_ln107_8_fu_759_p1;
wire    ap_block_pp0_stage12;
wire   [63:0] zext_ln107_9_fu_771_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage3;
reg   [31:0] empty_fu_96;
wire    ap_loop_init;
reg   [63:0] front_1_fu_100;
reg   [31:0] rear_1_fu_104;
wire    ap_block_pp0_stage1_01001;
wire   [31:0] trunc_ln100_fu_614_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [12:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_950;
reg    ap_condition_954;
reg    ap_condition_959;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

top_function_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage12_subdone) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_15_load_reg_973) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'd1 == adjacencyList_15_load_reg_973) & (1'b0 == ap_block_pp0_stage11_11001) & (visited_load_7_reg_1034 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11)))) begin
        ap_phi_reg_pp0_iter0_rear_7_14_reg_553 <= ap_phi_mux_rear_7_12_phi_fu_542_p6;
    end else if (((1'd1 == adjacencyList_15_load_reg_973) & (1'b0 == ap_block_pp0_stage11_11001) & (visited_load_7_reg_1034 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        ap_phi_reg_pp0_iter0_rear_7_14_reg_553 <= add_ln107_7_fu_741_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0))) begin
        if ((1'b1 == ap_condition_959)) begin
            ap_phi_reg_pp0_iter0_rear_7_6_reg_511 <= rear_7_3_reg_497;
        end else if ((1'b1 == ap_condition_954)) begin
            ap_phi_reg_pp0_iter0_rear_7_6_reg_511 <= ap_phi_mux_rear_7_3_phi_fu_500_p6;
        end else if ((1'b1 == ap_condition_950)) begin
            ap_phi_reg_pp0_iter0_rear_7_6_reg_511 <= add_ln107_4_fu_709_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_18_load_reg_981) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'd1 == adjacencyList_18_load_reg_981) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_load_9_reg_1042 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)))) begin
        ap_phi_reg_pp0_iter1_rear_7_17_reg_580 <= ap_phi_mux_rear_7_15_phi_fu_569_p6;
    end else if (((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        ap_phi_reg_pp0_iter1_rear_7_17_reg_580 <= ap_phi_reg_pp0_iter0_rear_7_17_reg_580;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_fu_96 <= p_reload30;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln100_reg_871 == 1'd0))) begin
            empty_fu_96 <= add_ln102_reg_940;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            front_1_fu_100 <= 64'd18446744073709551615;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln100_reg_871 == 1'd0))) begin
            front_1_fu_100 <= add_ln101_reg_875;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rear_1_fu_104 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln100_reg_871 == 1'd0))) begin
            rear_1_fu_104 <= ap_phi_mux_rear_7_17_phi_fu_583_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_16_load_reg_977) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'd1 == adjacencyList_16_load_reg_977) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_load_8_reg_1038 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)))) begin
        rear_7_15_reg_566 <= ap_phi_reg_pp0_iter0_rear_7_14_reg_553;
    end else if (((1'd1 == adjacencyList_16_load_reg_977) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_load_8_reg_1038 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        rear_7_15_reg_566 <= add_ln107_8_fu_752_p2;
    end else if ((~(icmp_ln100_reg_871 == 1'd1) & (1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        rear_7_15_reg_566 <= ap_phi_reg_pp0_iter0_rear_7_15_reg_566;
    end
end

always @ (posedge ap_clk) begin
    if ((((visited_q0 == 1'd1) & (1'd1 == adjacencyList_2_load_reg_949) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_2_load_reg_949) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        rear_7_1_reg_470 <= ap_phi_mux_rear_7_0_phi_fu_462_p6;
    end else if (((visited_q0 == 1'd0) & (1'd1 == adjacencyList_2_load_reg_949) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        rear_7_1_reg_470 <= add_ln107_1_fu_676_p2;
    end else if ((~(icmp_ln100_reg_871 == 1'd1) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        rear_7_1_reg_470 <= ap_phi_reg_pp0_iter0_rear_7_1_reg_470;
    end
end

always @ (posedge ap_clk) begin
    if ((((visited_q0 == 1'd1) & (1'd1 == adjacencyList_4_load_reg_957) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_4_load_reg_957) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        rear_7_3_reg_497 <= ap_phi_mux_rear_7_2_phi_fu_487_p6;
    end else if (((visited_q0 == 1'd0) & (1'd1 == adjacencyList_4_load_reg_957) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        rear_7_3_reg_497 <= add_ln107_3_fu_694_p2;
    end else if ((~(icmp_ln100_reg_871 == 1'd1) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        rear_7_3_reg_497 <= ap_phi_reg_pp0_iter0_rear_7_3_reg_497;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln100_fu_618_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln101_reg_875 <= add_ln101_fu_624_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln102_reg_940 <= add_ln102_fu_654_p2;
        adjacencyList_11_load_reg_965 <= adjacencyList_11_q0;
        adjacencyList_13_load_reg_969 <= adjacencyList_13_q0;
        adjacencyList_15_load_reg_973 <= adjacencyList_15_q0;
        adjacencyList_16_load_reg_977 <= adjacencyList_16_q0;
        adjacencyList_18_load_reg_981 <= adjacencyList_18_q0;
        adjacencyList_1_load_reg_945 <= adjacencyList_1_q0;
        adjacencyList_2_load_reg_949 <= adjacencyList_2_q0;
        adjacencyList_3_load_reg_953 <= adjacencyList_3_q0;
        adjacencyList_4_load_reg_957 <= adjacencyList_4_q0;
        adjacencyList_7_load_reg_961 <= adjacencyList_7_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((visited_q0 == 1'd0) & (1'd1 == adjacencyList_2_load_reg_949) & (1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        add_ln107_1_reg_993 <= add_ln107_1_fu_676_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((visited_q1 == 1'd0) & (1'd1 == adjacencyList_3_load_reg_953) & (1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln107_2_reg_1002 <= add_ln107_2_fu_687_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((visited_q0 == 1'd0) & (1'd1 == adjacencyList_4_load_reg_957) & (1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln107_3_reg_1011 <= add_ln107_3_fu_694_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_7_load_reg_961) & (1'b0 == ap_block_pp0_stage7_11001) & (visited_load_4_reg_1016 == 1'd0) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        add_ln107_4_reg_1024 <= add_ln107_4_fu_709_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_11_load_reg_965) & (1'b0 == ap_block_pp0_stage9_11001) & (visited_load_5_reg_1020 == 1'd0) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        add_ln107_5_reg_1046 <= add_ln107_5_fu_719_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_13_load_reg_969) & (1'b0 == ap_block_pp0_stage10_11001) & (visited_load_6_reg_1030 == 1'd0) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        add_ln107_6_reg_1051 <= add_ln107_6_fu_730_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_1_q0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter0_rear_7_0_reg_459 <= rear_reg_814;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_11_load_reg_965) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'd1 == adjacencyList_11_load_reg_965) & (1'b0 == ap_block_pp0_stage8_11001) & (visited_load_5_reg_1020 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        ap_phi_reg_pp0_iter0_rear_7_10_reg_525 <= ap_phi_reg_pp0_iter0_rear_7_6_reg_511;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_13_load_reg_969) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'd1 == adjacencyList_13_load_reg_969) & (1'b0 == ap_block_pp0_stage10_11001) & (visited_load_6_reg_1030 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10)))) begin
        ap_phi_reg_pp0_iter0_rear_7_12_reg_539 <= ap_phi_mux_rear_7_10_phi_fu_528_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_3_load_reg_953) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_phi_reg_pp0_iter0_rear_7_2_reg_484 <= ap_phi_mux_rear_7_1_phi_fu_473_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln100_reg_871 <= icmp_ln100_fu_618_p2;
        rear_reg_814 <= rear_1_fu_104;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        rear_7_6_reg_511 <= ap_phi_reg_pp0_iter0_rear_7_6_reg_511;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        traversalSize_load_reg_885 <= traversalSize_i;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_2_load_reg_949) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        visited_load_1_reg_989 <= visited_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_3_load_reg_953) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        visited_load_2_reg_998 <= visited_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_4_load_reg_957) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        visited_load_3_reg_1007 <= visited_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_7_load_reg_961) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        visited_load_4_reg_1016 <= visited_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_11_load_reg_965) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        visited_load_5_reg_1020 <= visited_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_13_load_reg_969) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        visited_load_6_reg_1030 <= visited_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_15_load_reg_973) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        visited_load_7_reg_1034 <= visited_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_16_load_reg_977) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        visited_load_8_reg_1038 <= visited_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_18_load_reg_981) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        visited_load_9_reg_1042 <= visited_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_1_load_reg_945) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        visited_load_reg_985 <= visited_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_11_ce0 = 1'b1;
    end else begin
        adjacencyList_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_13_ce0 = 1'b1;
    end else begin
        adjacencyList_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_15_ce0 = 1'b1;
    end else begin
        adjacencyList_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_16_ce0 = 1'b1;
    end else begin
        adjacencyList_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_18_ce0 = 1'b1;
    end else begin
        adjacencyList_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_1_ce0 = 1'b1;
    end else begin
        adjacencyList_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_2_ce0 = 1'b1;
    end else begin
        adjacencyList_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_3_ce0 = 1'b1;
    end else begin
        adjacencyList_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_4_ce0 = 1'b1;
    end else begin
        adjacencyList_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_7_ce0 = 1'b1;
    end else begin
        adjacencyList_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        allTraversal_ce0 = 1'b1;
    end else begin
        allTraversal_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        allTraversal_we0 = 1'b1;
    end else begin
        allTraversal_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln100_fu_618_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == adjacencyList_1_load_reg_945) & (icmp_ln100_reg_871 == 1'd0))) begin
        if ((visited_q1 == 1'd1)) begin
            ap_phi_mux_rear_7_0_phi_fu_462_p6 = rear_reg_814;
        end else if ((visited_q1 == 1'd0)) begin
            ap_phi_mux_rear_7_0_phi_fu_462_p6 = add_ln107_fu_665_p2;
        end else begin
            ap_phi_mux_rear_7_0_phi_fu_462_p6 = ap_phi_reg_pp0_iter0_rear_7_0_reg_459;
        end
    end else begin
        ap_phi_mux_rear_7_0_phi_fu_462_p6 = ap_phi_reg_pp0_iter0_rear_7_0_reg_459;
    end
end

always @ (*) begin
    if (((1'd1 == adjacencyList_11_load_reg_965) & (visited_load_5_reg_1020 == 1'd0) & (icmp_ln100_reg_871 == 1'd0))) begin
        ap_phi_mux_rear_7_10_phi_fu_528_p6 = add_ln107_5_reg_1046;
    end else begin
        ap_phi_mux_rear_7_10_phi_fu_528_p6 = ap_phi_reg_pp0_iter0_rear_7_10_reg_525;
    end
end

always @ (*) begin
    if (((1'd1 == adjacencyList_13_load_reg_969) & (visited_load_6_reg_1030 == 1'd0) & (icmp_ln100_reg_871 == 1'd0))) begin
        ap_phi_mux_rear_7_12_phi_fu_542_p6 = add_ln107_6_reg_1051;
    end else begin
        ap_phi_mux_rear_7_12_phi_fu_542_p6 = ap_phi_reg_pp0_iter0_rear_7_12_reg_539;
    end
end

always @ (*) begin
    if ((((1'd0 == adjacencyList_16_load_reg_977) & (icmp_ln100_reg_871 == 1'd0)) | ((1'd1 == adjacencyList_16_load_reg_977) & (visited_load_8_reg_1038 == 1'd1) & (icmp_ln100_reg_871 == 1'd0)))) begin
        ap_phi_mux_rear_7_15_phi_fu_569_p6 = ap_phi_reg_pp0_iter0_rear_7_14_reg_553;
    end else if (((1'd1 == adjacencyList_16_load_reg_977) & (visited_load_8_reg_1038 == 1'd0) & (icmp_ln100_reg_871 == 1'd0))) begin
        ap_phi_mux_rear_7_15_phi_fu_569_p6 = add_ln107_8_fu_752_p2;
    end else begin
        ap_phi_mux_rear_7_15_phi_fu_569_p6 = ap_phi_reg_pp0_iter0_rear_7_15_reg_566;
    end
end

always @ (*) begin
    if (((1'd1 == adjacencyList_18_load_reg_981) & (visited_load_9_reg_1042 == 1'd0) & (icmp_ln100_reg_871 == 1'd0))) begin
        ap_phi_mux_rear_7_17_phi_fu_583_p6 = add_ln107_9_fu_764_p2;
    end else begin
        ap_phi_mux_rear_7_17_phi_fu_583_p6 = ap_phi_reg_pp0_iter1_rear_7_17_reg_580;
    end
end

always @ (*) begin
    if ((((visited_q0 == 1'd1) & (1'd1 == adjacencyList_2_load_reg_949) & (icmp_ln100_reg_871 == 1'd0)) | ((1'd0 == adjacencyList_2_load_reg_949) & (icmp_ln100_reg_871 == 1'd0)))) begin
        ap_phi_mux_rear_7_1_phi_fu_473_p6 = ap_phi_mux_rear_7_0_phi_fu_462_p6;
    end else if (((visited_q0 == 1'd0) & (1'd1 == adjacencyList_2_load_reg_949) & (icmp_ln100_reg_871 == 1'd0))) begin
        ap_phi_mux_rear_7_1_phi_fu_473_p6 = add_ln107_1_fu_676_p2;
    end else begin
        ap_phi_mux_rear_7_1_phi_fu_473_p6 = ap_phi_reg_pp0_iter0_rear_7_1_reg_470;
    end
end

always @ (*) begin
    if (((1'd1 == adjacencyList_3_load_reg_953) & (icmp_ln100_reg_871 == 1'd0))) begin
        if ((visited_q1 == 1'd1)) begin
            ap_phi_mux_rear_7_2_phi_fu_487_p6 = rear_7_1_reg_470;
        end else if ((visited_q1 == 1'd0)) begin
            ap_phi_mux_rear_7_2_phi_fu_487_p6 = add_ln107_2_fu_687_p2;
        end else begin
            ap_phi_mux_rear_7_2_phi_fu_487_p6 = ap_phi_reg_pp0_iter0_rear_7_2_reg_484;
        end
    end else begin
        ap_phi_mux_rear_7_2_phi_fu_487_p6 = ap_phi_reg_pp0_iter0_rear_7_2_reg_484;
    end
end

always @ (*) begin
    if ((((1'd0 == adjacencyList_4_load_reg_957) & (icmp_ln100_reg_871 == 1'd0)) | ((visited_q0 == 1'd1) & (1'd1 == adjacencyList_4_load_reg_957) & (icmp_ln100_reg_871 == 1'd0)))) begin
        ap_phi_mux_rear_7_3_phi_fu_500_p6 = ap_phi_mux_rear_7_2_phi_fu_487_p6;
    end else if (((visited_q0 == 1'd0) & (1'd1 == adjacencyList_4_load_reg_957) & (icmp_ln100_reg_871 == 1'd0))) begin
        ap_phi_mux_rear_7_3_phi_fu_500_p6 = add_ln107_3_fu_694_p2;
    end else begin
        ap_phi_mux_rear_7_3_phi_fu_500_p6 = ap_phi_reg_pp0_iter0_rear_7_3_reg_497;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage12_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nodeQueue_address0 = zext_ln107_9_fu_771_p1;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        nodeQueue_address0 = zext_ln107_8_fu_759_p1;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        nodeQueue_address0 = zext_ln107_7_fu_747_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        nodeQueue_address0 = zext_ln107_6_fu_736_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        nodeQueue_address0 = zext_ln107_5_fu_725_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        nodeQueue_address0 = zext_ln107_4_fu_715_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        nodeQueue_address0 = zext_ln107_3_fu_705_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        nodeQueue_address0 = zext_ln107_2_fu_701_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        nodeQueue_address0 = zext_ln107_1_fu_683_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        nodeQueue_address0 = zext_ln107_fu_671_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        nodeQueue_address0 = add_ln101_fu_624_p2;
    end else begin
        nodeQueue_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        nodeQueue_ce0 = 1'b1;
    end else begin
        nodeQueue_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nodeQueue_d0 = 5'd18;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        nodeQueue_d0 = 5'd16;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        nodeQueue_d0 = 5'd15;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        nodeQueue_d0 = 5'd13;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        nodeQueue_d0 = 5'd11;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        nodeQueue_d0 = 5'd7;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        nodeQueue_d0 = 5'd4;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        nodeQueue_d0 = 5'd3;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        nodeQueue_d0 = 5'd2;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        nodeQueue_d0 = 5'd1;
    end else begin
        nodeQueue_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'd1 == adjacencyList_18_load_reg_981) & (1'b0 == ap_block_pp0_stage0_11001) & (visited_load_9_reg_1042 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'd1 == adjacencyList_16_load_reg_977) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_load_8_reg_1038 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'd1 == adjacencyList_15_load_reg_973) & (1'b0 == ap_block_pp0_stage11_11001) & (visited_load_7_reg_1034 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'd1 == adjacencyList_13_load_reg_969) & (1'b0 == ap_block_pp0_stage10_11001) & (visited_load_6_reg_1030 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'd1 == adjacencyList_11_load_reg_965) & (1'b0 == ap_block_pp0_stage9_11001) & (visited_load_5_reg_1020 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) 
    & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'd1 == adjacencyList_7_load_reg_961) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_load_4_reg_1016 == 1'd0) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'd1 == adjacencyList_4_load_reg_957) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_load_3_reg_1007 == 1'd0) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((visited_q1 == 1'd0) & (1'd1 == adjacencyList_1_load_reg_945) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'd1 == adjacencyList_3_load_reg_953) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_load_2_reg_998 == 1'd0) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'd1 == adjacencyList_2_load_reg_949) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 
    == 1'b1) & (visited_load_1_reg_989 == 1'd0) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        nodeQueue_we0 = 1'b1;
    end else begin
        nodeQueue_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln100_fu_618_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        traversalSize_o = add_ln102_fu_654_p2;
    end else begin
        traversalSize_o = traversalSize_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        traversalSize_o_ap_vld = 1'b1;
    end else begin
        traversalSize_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        visited_address0 = 64'd18;
    end else if ((((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        visited_address0 = 64'd15;
    end else if ((((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        visited_address0 = 64'd11;
    end else if ((((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        visited_address0 = 64'd4;
    end else if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        visited_address0 = 64'd2;
    end else begin
        visited_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        visited_address1 = 64'd16;
    end else if ((((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        visited_address1 = 64'd13;
    end else if ((((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        visited_address1 = 64'd7;
    end else if ((((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        visited_address1 = 64'd3;
    end else if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        visited_address1 = 64'd1;
    end else begin
        visited_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        visited_ce0 = 1'b1;
    end else begin
        visited_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        visited_ce1 = 1'b1;
    end else begin
        visited_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == adjacencyList_18_load_reg_981) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_load_9_reg_1042 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'd1 == adjacencyList_15_load_reg_973) & (1'b0 == ap_block_pp0_stage11_11001) & (visited_load_7_reg_1034 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'd1 == adjacencyList_11_load_reg_965) & (1'b0 == ap_block_pp0_stage10_11001) & (visited_load_5_reg_1020 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'd1 == adjacencyList_4_load_reg_957) & (1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_load_3_reg_1007 == 1'd0) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'd1 == adjacencyList_2_load_reg_949) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_load_1_reg_989 == 1'd0) 
    & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        visited_we0 = 1'b1;
    end else begin
        visited_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == adjacencyList_16_load_reg_977) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_load_8_reg_1038 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'd1 == adjacencyList_13_load_reg_969) & (1'b0 == ap_block_pp0_stage11_11001) & (visited_load_6_reg_1030 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'd1 == adjacencyList_7_load_reg_961) & (1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_load_4_reg_1016 == 1'd0) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'd1 == adjacencyList_3_load_reg_953) & (1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_load_2_reg_998 == 1'd0) & (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'd1 == adjacencyList_1_load_reg_945) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_load_reg_985 == 1'd0) & 
    (icmp_ln100_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        visited_we1 = 1'b1;
    end else begin
        visited_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln101_fu_624_p2 = (front_1_fu_100 + 64'd1);

assign add_ln102_fu_654_p2 = (traversalSize_load_reg_885 + 32'd1);

assign add_ln107_1_fu_676_p2 = (ap_phi_mux_rear_7_0_phi_fu_462_p6 + 32'd1);

assign add_ln107_2_fu_687_p2 = (rear_7_1_reg_470 + 32'd1);

assign add_ln107_3_fu_694_p2 = (ap_phi_mux_rear_7_2_phi_fu_487_p6 + 32'd1);

assign add_ln107_4_fu_709_p2 = (rear_7_3_reg_497 + 32'd1);

assign add_ln107_5_fu_719_p2 = (rear_7_6_reg_511 + 32'd1);

assign add_ln107_6_fu_730_p2 = (ap_phi_mux_rear_7_10_phi_fu_528_p6 + 32'd1);

assign add_ln107_7_fu_741_p2 = (ap_phi_mux_rear_7_12_phi_fu_542_p6 + 32'd1);

assign add_ln107_8_fu_752_p2 = (ap_phi_reg_pp0_iter0_rear_7_14_reg_553 + 32'd1);

assign add_ln107_9_fu_764_p2 = (rear_7_15_reg_566 + 32'd1);

assign add_ln107_fu_665_p2 = (rear_reg_814 + 32'd1);

assign adjacencyList_11_address0 = idxprom10_i64_cast_fu_640_p1;

assign adjacencyList_13_address0 = idxprom10_i64_cast_fu_640_p1;

assign adjacencyList_15_address0 = idxprom10_i64_cast_fu_640_p1;

assign adjacencyList_16_address0 = idxprom10_i64_cast_fu_640_p1;

assign adjacencyList_18_address0 = idxprom10_i64_cast_fu_640_p1;

assign adjacencyList_1_address0 = idxprom10_i64_cast_fu_640_p1;

assign adjacencyList_2_address0 = idxprom10_i64_cast_fu_640_p1;

assign adjacencyList_3_address0 = idxprom10_i64_cast_fu_640_p1;

assign adjacencyList_4_address0 = idxprom10_i64_cast_fu_640_p1;

assign adjacencyList_7_address0 = idxprom10_i64_cast_fu_640_p1;

assign allTraversal_address0 = zext_ln102_fu_635_p1;

assign allTraversal_d0 = nodeQueue_q0;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage10_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage11_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage12_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_950 = ((1'd1 == adjacencyList_7_load_reg_961) & (1'b0 == ap_block_pp0_stage7_11001) & (visited_load_4_reg_1016 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7));
end

always @ (*) begin
    ap_condition_954 = ((1'b0 == ap_block_pp0_stage5_11001) & (1'd0 == adjacencyList_7_load_reg_961) & (1'b1 == ap_CS_fsm_pp0_stage5));
end

always @ (*) begin
    ap_condition_959 = ((visited_q1 == 1'd1) & (1'd1 == adjacencyList_7_load_reg_961) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_phi_reg_pp0_iter0_rear_7_15_reg_566 = 'bx;

assign ap_phi_reg_pp0_iter0_rear_7_17_reg_580 = 'bx;

assign ap_phi_reg_pp0_iter0_rear_7_1_reg_470 = 'bx;

assign ap_phi_reg_pp0_iter0_rear_7_3_reg_497 = 'bx;

assign icmp_ln100_fu_618_p2 = ((trunc_ln100_fu_614_p1 == rear_1_fu_104) ? 1'b1 : 1'b0);

assign idxprom10_i64_cast_fu_640_p1 = nodeQueue_q0;

assign p_out = empty_fu_96;

assign trunc_ln100_fu_614_p1 = front_1_fu_100[31:0];

assign visited_d0 = 1'd1;

assign visited_d1 = 1'd1;

assign zext_ln102_fu_635_p1 = traversalSize_i;

assign zext_ln107_1_fu_683_p1 = add_ln107_1_reg_993;

assign zext_ln107_2_fu_701_p1 = add_ln107_2_reg_1002;

assign zext_ln107_3_fu_705_p1 = add_ln107_3_reg_1011;

assign zext_ln107_4_fu_715_p1 = add_ln107_4_reg_1024;

assign zext_ln107_5_fu_725_p1 = add_ln107_5_fu_719_p2;

assign zext_ln107_6_fu_736_p1 = add_ln107_6_fu_730_p2;

assign zext_ln107_7_fu_747_p1 = add_ln107_7_fu_741_p2;

assign zext_ln107_8_fu_759_p1 = add_ln107_8_fu_752_p2;

assign zext_ln107_9_fu_771_p1 = add_ln107_9_fu_764_p2;

assign zext_ln107_fu_671_p1 = add_ln107_fu_665_p2;

endmodule //top_function_top_function_Pipeline_VITIS_LOOP_100_1
