// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_function_top_function_Pipeline_VITIS_LOOP_37_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        visited_3_address0,
        visited_3_ce0,
        visited_3_we0,
        visited_3_d0,
        visited_3_q0,
        visited_3_address1,
        visited_3_ce1,
        visited_3_we1,
        visited_3_d1,
        visited_3_q1,
        queue_address0,
        queue_ce0,
        queue_we0,
        queue_d0,
        queue_q0,
        adjacencyList_18_address0,
        adjacencyList_18_ce0,
        adjacencyList_18_q0,
        adjacencyList_16_address0,
        adjacencyList_16_ce0,
        adjacencyList_16_q0,
        adjacencyList_15_address0,
        adjacencyList_15_ce0,
        adjacencyList_15_q0,
        adjacencyList_13_address0,
        adjacencyList_13_ce0,
        adjacencyList_13_q0,
        adjacencyList_11_address0,
        adjacencyList_11_ce0,
        adjacencyList_11_q0,
        adjacencyList_7_address0,
        adjacencyList_7_ce0,
        adjacencyList_7_q0,
        adjacencyList_4_address0,
        adjacencyList_4_ce0,
        adjacencyList_4_q0,
        adjacencyList_3_address0,
        adjacencyList_3_ce0,
        adjacencyList_3_q0,
        adjacencyList_2_address0,
        adjacencyList_2_ce0,
        adjacencyList_2_q0,
        traversalSize_i,
        traversalSize_o,
        traversalSize_o_ap_vld,
        allTraversal_address0,
        allTraversal_ce0,
        allTraversal_we0,
        allTraversal_d0,
        adjacencyList_1_address0,
        adjacencyList_1_ce0,
        adjacencyList_1_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 13'd1;
parameter    ap_ST_fsm_pp0_stage1 = 13'd2;
parameter    ap_ST_fsm_pp0_stage2 = 13'd4;
parameter    ap_ST_fsm_pp0_stage3 = 13'd8;
parameter    ap_ST_fsm_pp0_stage4 = 13'd16;
parameter    ap_ST_fsm_pp0_stage5 = 13'd32;
parameter    ap_ST_fsm_pp0_stage6 = 13'd64;
parameter    ap_ST_fsm_pp0_stage7 = 13'd128;
parameter    ap_ST_fsm_pp0_stage8 = 13'd256;
parameter    ap_ST_fsm_pp0_stage9 = 13'd512;
parameter    ap_ST_fsm_pp0_stage10 = 13'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 13'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] visited_3_address0;
output   visited_3_ce0;
output   visited_3_we0;
output  [0:0] visited_3_d0;
input  [0:0] visited_3_q0;
output  [4:0] visited_3_address1;
output   visited_3_ce1;
output   visited_3_we1;
output  [0:0] visited_3_d1;
input  [0:0] visited_3_q1;
output  [4:0] queue_address0;
output   queue_ce0;
output   queue_we0;
output  [4:0] queue_d0;
input  [4:0] queue_q0;
output  [4:0] adjacencyList_18_address0;
output   adjacencyList_18_ce0;
input  [0:0] adjacencyList_18_q0;
output  [4:0] adjacencyList_16_address0;
output   adjacencyList_16_ce0;
input  [0:0] adjacencyList_16_q0;
output  [4:0] adjacencyList_15_address0;
output   adjacencyList_15_ce0;
input  [0:0] adjacencyList_15_q0;
output  [4:0] adjacencyList_13_address0;
output   adjacencyList_13_ce0;
input  [0:0] adjacencyList_13_q0;
output  [4:0] adjacencyList_11_address0;
output   adjacencyList_11_ce0;
input  [0:0] adjacencyList_11_q0;
output  [4:0] adjacencyList_7_address0;
output   adjacencyList_7_ce0;
input  [0:0] adjacencyList_7_q0;
output  [4:0] adjacencyList_4_address0;
output   adjacencyList_4_ce0;
input  [0:0] adjacencyList_4_q0;
output  [4:0] adjacencyList_3_address0;
output   adjacencyList_3_ce0;
input  [0:0] adjacencyList_3_q0;
output  [4:0] adjacencyList_2_address0;
output   adjacencyList_2_ce0;
input  [0:0] adjacencyList_2_q0;
input  [31:0] traversalSize_i;
output  [31:0] traversalSize_o;
output   traversalSize_o_ap_vld;
output  [4:0] allTraversal_address0;
output   allTraversal_ce0;
output   allTraversal_we0;
output  [4:0] allTraversal_d0;
output  [4:0] adjacencyList_1_address0;
output   adjacencyList_1_ce0;
input  [0:0] adjacencyList_1_q0;

reg ap_idle;
reg[4:0] visited_3_address0;
reg visited_3_ce0;
reg visited_3_we0;
reg[4:0] visited_3_address1;
reg visited_3_ce1;
reg visited_3_we1;
reg[4:0] queue_address0;
reg queue_ce0;
reg queue_we0;
reg[4:0] queue_d0;
reg adjacencyList_18_ce0;
reg adjacencyList_16_ce0;
reg adjacencyList_15_ce0;
reg adjacencyList_13_ce0;
reg adjacencyList_11_ce0;
reg adjacencyList_7_ce0;
reg adjacencyList_4_ce0;
reg adjacencyList_3_ce0;
reg adjacencyList_2_ce0;
reg[31:0] traversalSize_o;
reg traversalSize_o_ap_vld;
reg allTraversal_ce0;
reg allTraversal_we0;
reg adjacencyList_1_ce0;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln37_fu_588_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_state13_pp0_stage12_iter0;
wire    ap_block_pp0_stage12_subdone;
reg   [31:0] rear_3_1_reg_445;
reg   [31:0] rear_3_3_reg_472;
reg   [31:0] rear_3_6_reg_486;
reg   [31:0] rear_3_15_reg_541;
reg   [31:0] rear_1_reg_770;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln37_reg_827;
wire   [63:0] add_ln38_fu_594_p2;
reg   [63:0] add_ln38_reg_831;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_pp0_stage2_11001;
reg   [0:0] adjacencyList_1_load_reg_891;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_pp0_stage3_11001;
reg   [0:0] adjacencyList_2_load_reg_895;
reg   [0:0] adjacencyList_3_load_reg_899;
reg   [0:0] adjacencyList_4_load_reg_903;
reg   [0:0] adjacencyList_7_load_reg_907;
reg   [0:0] adjacencyList_11_load_reg_911;
reg   [0:0] adjacencyList_13_load_reg_915;
reg   [0:0] adjacencyList_15_load_reg_919;
reg   [0:0] adjacencyList_16_load_reg_923;
reg   [0:0] adjacencyList_18_load_reg_927;
reg   [0:0] visited_3_load_reg_931;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_pp0_stage4_11001;
reg   [0:0] visited_3_load_1_reg_935;
wire   [31:0] add_ln44_1_fu_647_p2;
reg   [31:0] add_ln44_1_reg_939;
reg   [0:0] visited_3_load_2_reg_944;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_pp0_stage5_11001;
wire   [31:0] add_ln44_2_fu_658_p2;
reg   [31:0] add_ln44_2_reg_948;
reg   [0:0] visited_3_load_3_reg_953;
wire   [31:0] add_ln44_3_fu_665_p2;
reg   [31:0] add_ln44_3_reg_957;
reg   [0:0] visited_3_load_4_reg_962;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_pp0_stage6_11001;
reg   [0:0] visited_3_load_5_reg_966;
wire   [31:0] add_ln44_4_fu_680_p2;
reg   [31:0] add_ln44_4_reg_970;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_pp0_stage7_11001;
reg   [0:0] visited_3_load_6_reg_976;
reg   [0:0] visited_3_load_7_reg_980;
reg   [0:0] visited_3_load_8_reg_984;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state9_pp0_stage8_iter0;
wire    ap_block_pp0_stage8_11001;
reg   [0:0] visited_3_load_9_reg_988;
wire   [31:0] add_ln44_5_fu_690_p2;
reg   [31:0] add_ln44_5_reg_992;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_state10_pp0_stage9_iter0;
wire    ap_block_pp0_stage9_11001;
wire   [31:0] add_ln44_6_fu_701_p2;
reg   [31:0] add_ln44_6_reg_997;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_state11_pp0_stage10_iter0;
wire    ap_block_pp0_stage10_11001;
wire   [31:0] add_ln44_7_fu_712_p2;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_state12_pp0_stage11_iter0;
wire    ap_block_pp0_stage11_11001;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state14_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg   [31:0] ap_phi_mux_rear_3_0_phi_fu_437_p6;
wire   [31:0] add_ln44_fu_636_p2;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_3_0_reg_434;
reg   [31:0] ap_phi_mux_rear_3_1_phi_fu_448_p6;
wire   [31:0] ap_phi_reg_pp0_iter0_rear_3_1_reg_445;
reg   [31:0] ap_phi_mux_rear_3_2_phi_fu_462_p6;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_3_2_reg_459;
reg   [31:0] ap_phi_mux_rear_3_3_phi_fu_475_p6;
wire   [31:0] ap_phi_reg_pp0_iter0_rear_3_3_reg_472;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_3_6_reg_486;
reg   [31:0] ap_phi_mux_rear_3_10_phi_fu_503_p6;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_3_10_reg_500;
reg   [31:0] ap_phi_mux_rear_3_12_phi_fu_517_p6;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_3_12_reg_514;
reg   [31:0] ap_phi_reg_pp0_iter0_rear_3_14_reg_528;
wire    ap_block_pp0_stage12_11001;
reg   [31:0] ap_phi_mux_rear_3_15_phi_fu_544_p6;
wire   [31:0] add_ln44_8_fu_723_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_rear_3_15_reg_541;
reg   [31:0] ap_phi_mux_rear_3_17_phi_fu_558_p6;
wire   [31:0] add_ln44_9_fu_735_p2;
reg   [31:0] ap_phi_reg_pp0_iter1_rear_3_17_reg_555;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] ap_phi_reg_pp0_iter0_rear_3_17_reg_555;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln39_fu_617_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] idxprom10_i_cast_fu_622_p1;
wire   [63:0] zext_ln44_fu_642_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln44_1_fu_654_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln44_2_fu_672_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln44_3_fu_676_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln44_4_fu_686_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln44_5_fu_696_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln44_6_fu_707_p1;
wire    ap_block_pp0_stage10;
wire   [63:0] zext_ln44_7_fu_718_p1;
wire    ap_block_pp0_stage11;
wire   [63:0] zext_ln44_8_fu_730_p1;
wire    ap_block_pp0_stage12;
wire   [63:0] zext_ln44_9_fu_742_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] add_ln39_fu_605_p2;
reg   [63:0] front_fu_88;
wire    ap_loop_init;
reg   [31:0] rear_fu_92;
wire    ap_block_pp0_stage3;
wire   [31:0] trunc_ln37_fu_584_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [12:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_931;
reg    ap_condition_935;
reg    ap_condition_940;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

top_function_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage12_subdone) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_15_load_reg_919) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'd1 == adjacencyList_15_load_reg_919) & (1'b0 == ap_block_pp0_stage11_11001) & (visited_3_load_7_reg_980 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11)))) begin
        ap_phi_reg_pp0_iter0_rear_3_14_reg_528 <= ap_phi_mux_rear_3_12_phi_fu_517_p6;
    end else if (((1'd1 == adjacencyList_15_load_reg_919) & (1'b0 == ap_block_pp0_stage11_11001) & (visited_3_load_7_reg_980 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        ap_phi_reg_pp0_iter0_rear_3_14_reg_528 <= add_ln44_7_fu_712_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0))) begin
        if ((1'b1 == ap_condition_940)) begin
            ap_phi_reg_pp0_iter0_rear_3_6_reg_486 <= rear_3_3_reg_472;
        end else if ((1'b1 == ap_condition_935)) begin
            ap_phi_reg_pp0_iter0_rear_3_6_reg_486 <= ap_phi_mux_rear_3_3_phi_fu_475_p6;
        end else if ((1'b1 == ap_condition_931)) begin
            ap_phi_reg_pp0_iter0_rear_3_6_reg_486 <= add_ln44_4_fu_680_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_18_load_reg_927) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'd1 == adjacencyList_18_load_reg_927) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_3_load_9_reg_988 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)))) begin
        ap_phi_reg_pp0_iter1_rear_3_17_reg_555 <= ap_phi_mux_rear_3_15_phi_fu_544_p6;
    end else if (((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        ap_phi_reg_pp0_iter1_rear_3_17_reg_555 <= ap_phi_reg_pp0_iter0_rear_3_17_reg_555;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            front_fu_88 <= 64'd18446744073709551615;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln37_reg_827 == 1'd0))) begin
            front_fu_88 <= add_ln38_reg_831;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_16_load_reg_923) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'd1 == adjacencyList_16_load_reg_923) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_3_load_8_reg_984 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)))) begin
        rear_3_15_reg_541 <= ap_phi_reg_pp0_iter0_rear_3_14_reg_528;
    end else if (((1'd1 == adjacencyList_16_load_reg_923) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_3_load_8_reg_984 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        rear_3_15_reg_541 <= add_ln44_8_fu_723_p2;
    end else if ((~(icmp_ln37_reg_827 == 1'd1) & (1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        rear_3_15_reg_541 <= ap_phi_reg_pp0_iter0_rear_3_15_reg_541;
    end
end

always @ (posedge ap_clk) begin
    if ((((visited_3_q0 == 1'd1) & (1'd1 == adjacencyList_2_load_reg_895) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_2_load_reg_895) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        rear_3_1_reg_445 <= ap_phi_mux_rear_3_0_phi_fu_437_p6;
    end else if (((visited_3_q0 == 1'd0) & (1'd1 == adjacencyList_2_load_reg_895) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        rear_3_1_reg_445 <= add_ln44_1_fu_647_p2;
    end else if ((~(icmp_ln37_reg_827 == 1'd1) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        rear_3_1_reg_445 <= ap_phi_reg_pp0_iter0_rear_3_1_reg_445;
    end
end

always @ (posedge ap_clk) begin
    if ((((visited_3_q0 == 1'd1) & (1'd1 == adjacencyList_4_load_reg_903) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_4_load_reg_903) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        rear_3_3_reg_472 <= ap_phi_mux_rear_3_2_phi_fu_462_p6;
    end else if (((visited_3_q0 == 1'd0) & (1'd1 == adjacencyList_4_load_reg_903) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        rear_3_3_reg_472 <= add_ln44_3_fu_665_p2;
    end else if ((~(icmp_ln37_reg_827 == 1'd1) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        rear_3_3_reg_472 <= ap_phi_reg_pp0_iter0_rear_3_3_reg_472;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rear_fu_92 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln37_reg_827 == 1'd0))) begin
            rear_fu_92 <= ap_phi_mux_rear_3_17_phi_fu_558_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_588_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln38_reg_831 <= add_ln38_fu_594_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((visited_3_q0 == 1'd0) & (1'd1 == adjacencyList_2_load_reg_895) & (1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        add_ln44_1_reg_939 <= add_ln44_1_fu_647_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((visited_3_q1 == 1'd0) & (1'd1 == adjacencyList_3_load_reg_899) & (1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln44_2_reg_948 <= add_ln44_2_fu_658_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((visited_3_q0 == 1'd0) & (1'd1 == adjacencyList_4_load_reg_903) & (1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln44_3_reg_957 <= add_ln44_3_fu_665_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_7_load_reg_907) & (1'b0 == ap_block_pp0_stage7_11001) & (visited_3_load_4_reg_962 == 1'd0) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        add_ln44_4_reg_970 <= add_ln44_4_fu_680_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_11_load_reg_911) & (1'b0 == ap_block_pp0_stage9_11001) & (visited_3_load_5_reg_966 == 1'd0) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        add_ln44_5_reg_992 <= add_ln44_5_fu_690_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_13_load_reg_915) & (1'b0 == ap_block_pp0_stage10_11001) & (visited_3_load_6_reg_976 == 1'd0) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        add_ln44_6_reg_997 <= add_ln44_6_fu_701_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        adjacencyList_11_load_reg_911 <= adjacencyList_11_q0;
        adjacencyList_13_load_reg_915 <= adjacencyList_13_q0;
        adjacencyList_15_load_reg_919 <= adjacencyList_15_q0;
        adjacencyList_16_load_reg_923 <= adjacencyList_16_q0;
        adjacencyList_18_load_reg_927 <= adjacencyList_18_q0;
        adjacencyList_1_load_reg_891 <= adjacencyList_1_q0;
        adjacencyList_2_load_reg_895 <= adjacencyList_2_q0;
        adjacencyList_3_load_reg_899 <= adjacencyList_3_q0;
        adjacencyList_4_load_reg_903 <= adjacencyList_4_q0;
        adjacencyList_7_load_reg_907 <= adjacencyList_7_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_1_q0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter0_rear_3_0_reg_434 <= rear_1_reg_770;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_11_load_reg_911) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'd1 == adjacencyList_11_load_reg_911) & (1'b0 == ap_block_pp0_stage8_11001) & (visited_3_load_5_reg_966 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        ap_phi_reg_pp0_iter0_rear_3_10_reg_500 <= ap_phi_reg_pp0_iter0_rear_3_6_reg_486;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_13_load_reg_915) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'd1 == adjacencyList_13_load_reg_915) & (1'b0 == ap_block_pp0_stage10_11001) & (visited_3_load_6_reg_976 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10)))) begin
        ap_phi_reg_pp0_iter0_rear_3_12_reg_514 <= ap_phi_mux_rear_3_10_phi_fu_503_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'd0 == adjacencyList_3_load_reg_899) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_phi_reg_pp0_iter0_rear_3_2_reg_459 <= ap_phi_mux_rear_3_1_phi_fu_448_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln37_reg_827 <= icmp_ln37_fu_588_p2;
        rear_1_reg_770 <= rear_fu_92;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        rear_3_6_reg_486 <= ap_phi_reg_pp0_iter0_rear_3_6_reg_486;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_2_load_reg_895) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        visited_3_load_1_reg_935 <= visited_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_3_load_reg_899) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        visited_3_load_2_reg_944 <= visited_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_4_load_reg_903) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        visited_3_load_3_reg_953 <= visited_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_7_load_reg_907) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        visited_3_load_4_reg_962 <= visited_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_11_load_reg_911) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        visited_3_load_5_reg_966 <= visited_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_13_load_reg_915) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        visited_3_load_6_reg_976 <= visited_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_15_load_reg_919) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        visited_3_load_7_reg_980 <= visited_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_16_load_reg_923) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        visited_3_load_8_reg_984 <= visited_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_18_load_reg_927) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        visited_3_load_9_reg_988 <= visited_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == adjacencyList_1_load_reg_891) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        visited_3_load_reg_931 <= visited_3_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_11_ce0 = 1'b1;
    end else begin
        adjacencyList_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_13_ce0 = 1'b1;
    end else begin
        adjacencyList_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_15_ce0 = 1'b1;
    end else begin
        adjacencyList_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_16_ce0 = 1'b1;
    end else begin
        adjacencyList_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_18_ce0 = 1'b1;
    end else begin
        adjacencyList_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_1_ce0 = 1'b1;
    end else begin
        adjacencyList_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_2_ce0 = 1'b1;
    end else begin
        adjacencyList_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_3_ce0 = 1'b1;
    end else begin
        adjacencyList_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_4_ce0 = 1'b1;
    end else begin
        adjacencyList_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        adjacencyList_7_ce0 = 1'b1;
    end else begin
        adjacencyList_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        allTraversal_ce0 = 1'b1;
    end else begin
        allTraversal_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        allTraversal_we0 = 1'b1;
    end else begin
        allTraversal_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_fu_588_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == adjacencyList_1_load_reg_891) & (icmp_ln37_reg_827 == 1'd0))) begin
        if ((visited_3_q1 == 1'd1)) begin
            ap_phi_mux_rear_3_0_phi_fu_437_p6 = rear_1_reg_770;
        end else if ((visited_3_q1 == 1'd0)) begin
            ap_phi_mux_rear_3_0_phi_fu_437_p6 = add_ln44_fu_636_p2;
        end else begin
            ap_phi_mux_rear_3_0_phi_fu_437_p6 = ap_phi_reg_pp0_iter0_rear_3_0_reg_434;
        end
    end else begin
        ap_phi_mux_rear_3_0_phi_fu_437_p6 = ap_phi_reg_pp0_iter0_rear_3_0_reg_434;
    end
end

always @ (*) begin
    if (((1'd1 == adjacencyList_11_load_reg_911) & (visited_3_load_5_reg_966 == 1'd0) & (icmp_ln37_reg_827 == 1'd0))) begin
        ap_phi_mux_rear_3_10_phi_fu_503_p6 = add_ln44_5_reg_992;
    end else begin
        ap_phi_mux_rear_3_10_phi_fu_503_p6 = ap_phi_reg_pp0_iter0_rear_3_10_reg_500;
    end
end

always @ (*) begin
    if (((1'd1 == adjacencyList_13_load_reg_915) & (visited_3_load_6_reg_976 == 1'd0) & (icmp_ln37_reg_827 == 1'd0))) begin
        ap_phi_mux_rear_3_12_phi_fu_517_p6 = add_ln44_6_reg_997;
    end else begin
        ap_phi_mux_rear_3_12_phi_fu_517_p6 = ap_phi_reg_pp0_iter0_rear_3_12_reg_514;
    end
end

always @ (*) begin
    if ((((1'd0 == adjacencyList_16_load_reg_923) & (icmp_ln37_reg_827 == 1'd0)) | ((1'd1 == adjacencyList_16_load_reg_923) & (visited_3_load_8_reg_984 == 1'd1) & (icmp_ln37_reg_827 == 1'd0)))) begin
        ap_phi_mux_rear_3_15_phi_fu_544_p6 = ap_phi_reg_pp0_iter0_rear_3_14_reg_528;
    end else if (((1'd1 == adjacencyList_16_load_reg_923) & (visited_3_load_8_reg_984 == 1'd0) & (icmp_ln37_reg_827 == 1'd0))) begin
        ap_phi_mux_rear_3_15_phi_fu_544_p6 = add_ln44_8_fu_723_p2;
    end else begin
        ap_phi_mux_rear_3_15_phi_fu_544_p6 = ap_phi_reg_pp0_iter0_rear_3_15_reg_541;
    end
end

always @ (*) begin
    if (((1'd1 == adjacencyList_18_load_reg_927) & (visited_3_load_9_reg_988 == 1'd0) & (icmp_ln37_reg_827 == 1'd0))) begin
        ap_phi_mux_rear_3_17_phi_fu_558_p6 = add_ln44_9_fu_735_p2;
    end else begin
        ap_phi_mux_rear_3_17_phi_fu_558_p6 = ap_phi_reg_pp0_iter1_rear_3_17_reg_555;
    end
end

always @ (*) begin
    if ((((visited_3_q0 == 1'd1) & (1'd1 == adjacencyList_2_load_reg_895) & (icmp_ln37_reg_827 == 1'd0)) | ((1'd0 == adjacencyList_2_load_reg_895) & (icmp_ln37_reg_827 == 1'd0)))) begin
        ap_phi_mux_rear_3_1_phi_fu_448_p6 = ap_phi_mux_rear_3_0_phi_fu_437_p6;
    end else if (((visited_3_q0 == 1'd0) & (1'd1 == adjacencyList_2_load_reg_895) & (icmp_ln37_reg_827 == 1'd0))) begin
        ap_phi_mux_rear_3_1_phi_fu_448_p6 = add_ln44_1_fu_647_p2;
    end else begin
        ap_phi_mux_rear_3_1_phi_fu_448_p6 = ap_phi_reg_pp0_iter0_rear_3_1_reg_445;
    end
end

always @ (*) begin
    if (((1'd1 == adjacencyList_3_load_reg_899) & (icmp_ln37_reg_827 == 1'd0))) begin
        if ((visited_3_q1 == 1'd1)) begin
            ap_phi_mux_rear_3_2_phi_fu_462_p6 = rear_3_1_reg_445;
        end else if ((visited_3_q1 == 1'd0)) begin
            ap_phi_mux_rear_3_2_phi_fu_462_p6 = add_ln44_2_fu_658_p2;
        end else begin
            ap_phi_mux_rear_3_2_phi_fu_462_p6 = ap_phi_reg_pp0_iter0_rear_3_2_reg_459;
        end
    end else begin
        ap_phi_mux_rear_3_2_phi_fu_462_p6 = ap_phi_reg_pp0_iter0_rear_3_2_reg_459;
    end
end

always @ (*) begin
    if ((((1'd0 == adjacencyList_4_load_reg_903) & (icmp_ln37_reg_827 == 1'd0)) | ((visited_3_q0 == 1'd1) & (1'd1 == adjacencyList_4_load_reg_903) & (icmp_ln37_reg_827 == 1'd0)))) begin
        ap_phi_mux_rear_3_3_phi_fu_475_p6 = ap_phi_mux_rear_3_2_phi_fu_462_p6;
    end else if (((visited_3_q0 == 1'd0) & (1'd1 == adjacencyList_4_load_reg_903) & (icmp_ln37_reg_827 == 1'd0))) begin
        ap_phi_mux_rear_3_3_phi_fu_475_p6 = add_ln44_3_fu_665_p2;
    end else begin
        ap_phi_mux_rear_3_3_phi_fu_475_p6 = ap_phi_reg_pp0_iter0_rear_3_3_reg_472;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage12_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        queue_address0 = zext_ln44_9_fu_742_p1;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        queue_address0 = zext_ln44_8_fu_730_p1;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        queue_address0 = zext_ln44_7_fu_718_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        queue_address0 = zext_ln44_6_fu_707_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        queue_address0 = zext_ln44_5_fu_696_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        queue_address0 = zext_ln44_4_fu_686_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        queue_address0 = zext_ln44_3_fu_676_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        queue_address0 = zext_ln44_2_fu_672_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        queue_address0 = zext_ln44_1_fu_654_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        queue_address0 = zext_ln44_fu_642_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        queue_address0 = add_ln38_fu_594_p2;
    end else begin
        queue_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        queue_ce0 = 1'b1;
    end else begin
        queue_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        queue_d0 = 5'd18;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        queue_d0 = 5'd16;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        queue_d0 = 5'd15;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        queue_d0 = 5'd13;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        queue_d0 = 5'd11;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        queue_d0 = 5'd7;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        queue_d0 = 5'd4;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        queue_d0 = 5'd3;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        queue_d0 = 5'd2;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        queue_d0 = 5'd1;
    end else begin
        queue_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'd1 == adjacencyList_18_load_reg_927) & (1'b0 == ap_block_pp0_stage0_11001) & (visited_3_load_9_reg_988 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'd1 == adjacencyList_16_load_reg_923) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_3_load_8_reg_984 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'd1 == adjacencyList_15_load_reg_919) & (1'b0 == ap_block_pp0_stage11_11001) & (visited_3_load_7_reg_980 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'd1 == adjacencyList_13_load_reg_915) & (1'b0 == ap_block_pp0_stage10_11001) & (visited_3_load_6_reg_976 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'd1 == adjacencyList_11_load_reg_911) & (1'b0 == ap_block_pp0_stage9_11001) & (visited_3_load_5_reg_966 == 1'd0) & (ap_enable_reg_pp0_iter0 == 
    1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'd1 == adjacencyList_7_load_reg_907) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_3_load_4_reg_962 == 1'd0) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'd1 == adjacencyList_4_load_reg_903) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_3_load_3_reg_953 == 1'd0) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((visited_3_q1 == 1'd0) & (1'd1 == adjacencyList_1_load_reg_891) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'd1 == adjacencyList_3_load_reg_899) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_3_load_2_reg_944 == 1'd0) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'd1 == adjacencyList_2_load_reg_895) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 
    == 1'b1) & (visited_3_load_1_reg_935 == 1'd0) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        queue_we0 = 1'b1;
    end else begin
        queue_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        traversalSize_o = add_ln39_fu_605_p2;
    end else begin
        traversalSize_o = traversalSize_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        traversalSize_o_ap_vld = 1'b1;
    end else begin
        traversalSize_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        visited_3_address0 = 64'd18;
    end else if ((((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        visited_3_address0 = 64'd15;
    end else if ((((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        visited_3_address0 = 64'd11;
    end else if ((((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        visited_3_address0 = 64'd4;
    end else if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        visited_3_address0 = 64'd2;
    end else begin
        visited_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        visited_3_address1 = 64'd16;
    end else if ((((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        visited_3_address1 = 64'd13;
    end else if ((((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        visited_3_address1 = 64'd7;
    end else if ((((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        visited_3_address1 = 64'd3;
    end else if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        visited_3_address1 = 64'd1;
    end else begin
        visited_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        visited_3_ce0 = 1'b1;
    end else begin
        visited_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        visited_3_ce1 = 1'b1;
    end else begin
        visited_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == adjacencyList_18_load_reg_927) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_3_load_9_reg_988 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'd1 == adjacencyList_15_load_reg_919) & (1'b0 == ap_block_pp0_stage11_11001) & (visited_3_load_7_reg_980 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'd1 == adjacencyList_11_load_reg_911) & (1'b0 == ap_block_pp0_stage10_11001) & (visited_3_load_5_reg_966 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'd1 == adjacencyList_4_load_reg_903) & (1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_3_load_3_reg_953 == 1'd0) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'd1 == adjacencyList_2_load_reg_895) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_3_load_1_reg_935 == 1'd0) 
    & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        visited_3_we0 = 1'b1;
    end else begin
        visited_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == adjacencyList_16_load_reg_923) & (1'b0 == ap_block_pp0_stage12_11001) & (visited_3_load_8_reg_984 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'd1 == adjacencyList_13_load_reg_915) & (1'b0 == ap_block_pp0_stage11_11001) & (visited_3_load_6_reg_976 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'd1 == adjacencyList_7_load_reg_907) & (1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_3_load_4_reg_962 == 1'd0) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'd1 == adjacencyList_3_load_reg_899) & (1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_3_load_2_reg_944 == 1'd0) & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'd1 == adjacencyList_1_load_reg_891) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (visited_3_load_reg_931 == 1'd0) 
    & (icmp_ln37_reg_827 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        visited_3_we1 = 1'b1;
    end else begin
        visited_3_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln38_fu_594_p2 = (front_fu_88 + 64'd1);

assign add_ln39_fu_605_p2 = (traversalSize_i + 32'd1);

assign add_ln44_1_fu_647_p2 = (ap_phi_mux_rear_3_0_phi_fu_437_p6 + 32'd1);

assign add_ln44_2_fu_658_p2 = (rear_3_1_reg_445 + 32'd1);

assign add_ln44_3_fu_665_p2 = (ap_phi_mux_rear_3_2_phi_fu_462_p6 + 32'd1);

assign add_ln44_4_fu_680_p2 = (rear_3_3_reg_472 + 32'd1);

assign add_ln44_5_fu_690_p2 = (rear_3_6_reg_486 + 32'd1);

assign add_ln44_6_fu_701_p2 = (ap_phi_mux_rear_3_10_phi_fu_503_p6 + 32'd1);

assign add_ln44_7_fu_712_p2 = (ap_phi_mux_rear_3_12_phi_fu_517_p6 + 32'd1);

assign add_ln44_8_fu_723_p2 = (ap_phi_reg_pp0_iter0_rear_3_14_reg_528 + 32'd1);

assign add_ln44_9_fu_735_p2 = (rear_3_15_reg_541 + 32'd1);

assign add_ln44_fu_636_p2 = (rear_1_reg_770 + 32'd1);

assign adjacencyList_11_address0 = idxprom10_i_cast_fu_622_p1;

assign adjacencyList_13_address0 = idxprom10_i_cast_fu_622_p1;

assign adjacencyList_15_address0 = idxprom10_i_cast_fu_622_p1;

assign adjacencyList_16_address0 = idxprom10_i_cast_fu_622_p1;

assign adjacencyList_18_address0 = idxprom10_i_cast_fu_622_p1;

assign adjacencyList_1_address0 = idxprom10_i_cast_fu_622_p1;

assign adjacencyList_2_address0 = idxprom10_i_cast_fu_622_p1;

assign adjacencyList_3_address0 = idxprom10_i_cast_fu_622_p1;

assign adjacencyList_4_address0 = idxprom10_i_cast_fu_622_p1;

assign adjacencyList_7_address0 = idxprom10_i_cast_fu_622_p1;

assign allTraversal_address0 = zext_ln39_fu_617_p1;

assign allTraversal_d0 = queue_q0;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage10_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage11_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage12_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_931 = ((1'd1 == adjacencyList_7_load_reg_907) & (1'b0 == ap_block_pp0_stage7_11001) & (visited_3_load_4_reg_962 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7));
end

always @ (*) begin
    ap_condition_935 = ((1'b0 == ap_block_pp0_stage5_11001) & (1'd0 == adjacencyList_7_load_reg_907) & (1'b1 == ap_CS_fsm_pp0_stage5));
end

always @ (*) begin
    ap_condition_940 = ((visited_3_q1 == 1'd1) & (1'd1 == adjacencyList_7_load_reg_907) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_phi_reg_pp0_iter0_rear_3_15_reg_541 = 'bx;

assign ap_phi_reg_pp0_iter0_rear_3_17_reg_555 = 'bx;

assign ap_phi_reg_pp0_iter0_rear_3_1_reg_445 = 'bx;

assign ap_phi_reg_pp0_iter0_rear_3_3_reg_472 = 'bx;

assign icmp_ln37_fu_588_p2 = ((trunc_ln37_fu_584_p1 == rear_fu_92) ? 1'b1 : 1'b0);

assign idxprom10_i_cast_fu_622_p1 = queue_q0;

assign trunc_ln37_fu_584_p1 = front_fu_88[31:0];

assign visited_3_d0 = 1'd1;

assign visited_3_d1 = 1'd1;

assign zext_ln39_fu_617_p1 = traversalSize_i;

assign zext_ln44_1_fu_654_p1 = add_ln44_1_reg_939;

assign zext_ln44_2_fu_672_p1 = add_ln44_2_reg_948;

assign zext_ln44_3_fu_676_p1 = add_ln44_3_reg_957;

assign zext_ln44_4_fu_686_p1 = add_ln44_4_reg_970;

assign zext_ln44_5_fu_696_p1 = add_ln44_5_fu_690_p2;

assign zext_ln44_6_fu_707_p1 = add_ln44_6_fu_701_p2;

assign zext_ln44_7_fu_718_p1 = add_ln44_7_fu_712_p2;

assign zext_ln44_8_fu_730_p1 = add_ln44_8_fu_723_p2;

assign zext_ln44_9_fu_742_p1 = add_ln44_9_fu_735_p2;

assign zext_ln44_fu_642_p1 = add_ln44_fu_636_p2;

endmodule //top_function_top_function_Pipeline_VITIS_LOOP_37_1
